"""
Django settings for job_tracker project.
Generated by 'django-admin startproject' using Django 5.2.3.
"""

import os
from pathlib import Path

# 📁 Base Directory
BASE_DIR = Path(__file__).resolve().parent.parent

# 🔐 SECRET KEY (Change in Production)
SECRET_KEY = 'django-insecure-kc7t!f43pw#3$(hc=&*d@oa89+2t01!o6v@e-6&tobx_*myk@9'

# ⚠️ Debug Mode (False in production)
DEBUG = True

ALLOWED_HOSTS = []

# ✅ Installed Apps
INSTALLED_APPS = [
    'jazzmin',  # 🎨 Beautiful Admin Panel
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 🔧 3rd-party Tools
    'widget_tweaks',  # For Bootstrap-styled forms

    # 🌟 Your Applications
    'jobapp',
]

# 🌐 Middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 🌍 Root URL Config
ROOT_URLCONF = 'job_tracker.urls'

# 🎨 Templates Configuration
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Global templates folder
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # ✅ Custom: Include current year in footer
                'job_tracker.context_processors.current_year',
            ],
        },
    },
]

# 🚀 WSGI
WSGI_APPLICATION = 'job_tracker.wsgi.application'

# 🗂 Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# 🔑 Password Validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# 🌐 Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'  # 🇮🇳 Update to your TZ
USE_I18N = True
USE_TZ = True

# 📁 Static Files (CSS, JS)
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# 📂 Media Files (Resume Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 🔐 Auth & Redirects
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# 🆔 Auto Field Default
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 🎨 Jazzmin Admin Theme (Optional)
JAZZMIN_SETTINGS = {
    "site_title": "JobTracker Admin",
    "site_header": "JobTracker Dashboard",
    "site_brand": "JobTracker",
    "welcome_sign": "Welcome to JobTracker Admin",
    "copyright": "© 2025",
    "search_model": ["auth.User", "jobapp.JobApplication"],
    "topmenu_links": [
        {"name": "Home", "url": "/", "permissions": ["auth.view_user"]},
    ],
}